version: '1'
services:
  
  chrome:
    image: ashokpaik/seleniumpytest
    depends_on:
      - hub
    ports:
      - "6442:5900"
    environment:
      HUB_HOST: hub
    command:
      COPY . /Final
    command:
      WORKDIR /Final
    command:
      RUN pip install --no-cache-dir -r requirements.txt
    command: 
      RUN ["pytest", "--cache-clear", "--html=report.html", "-v", "-n=1", "--junit-xml=result.xml"]
    command:
      tail -f /dev/null
      
  hub:
    image: ashokpaik/seleniumpytest
    ports:
      - "4444:4444"
    command: 
      tail -f /dev/null
