version: '1'
services:
  
  chrome:
    image: ashokpaik/seleniumpytest
    depends_on:
      - hub
    ports:
      - "6442:5900"
    environment:
      HUB_HOST: hub
          
  hub:
    image: ashokpaik/seleniumpytest
    ports:
      - "4444:4444"
    
